id: IAA4D66D1
legacy_id: P005486
ocr_import_info:
  bdrc_scan_id: W22351
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T22:59:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T21:25:19.266602+00:00'
last_modified: 2022-09-02 05:25:35.210796
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22351
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22351
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསླབ་པ་ཀུན་ལས་བཏུས་པ་ཞེས་བྱ་བ་རྒྱལ་སྲས་ཞི་བ་ལྷས་མཛད་པ།
  author: རྒྱལ་སྲས་ཞི་བ་ལྷ།
statistics:
  ocr_word_mean_confidence_index: 0.6045458354051054
  ocr_word_median_confidence_index: 0.6399999856948853
quality: null
bases:
  I1KG469:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG469
      total_pages: 542
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG469.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6045458354051054
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
