id: P005486
initial_creation_type: ocr
source_metadata:
  id: bdr:W22351
  title: བསླབ་པ་ཀུན་ལས་བཏུས་པ་ཞེས་བྱ་བ་རྒྱལ་སྲས་ཞི་བ་ལྷས་མཛད་པ།
  author: ''
  volumes:
    79b9c1c79ea944a9b83198ccc55d8dff:
      image_group_id: I1KG469
      title: ''
      volume_number: 1
      total_pages: 542
      base_file: v001.txt
